name: 'package-lock.json root validator'

on:
  push:
    branches: [master, main]
    paths:
      - '**/package-lock.json'
      - '!utils/atomic-storybook/package-lock.json'
      - '!package-lock.json'
  pull_request:
    branches: [master, main]
    paths:
      - '**/package-lock.json'
      - '!utils/atomic-storybook/package-lock.json'
      - '!package-lock.json'

permissions:
  contents: read

jobs:
  lockfile-outside-of-root:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: exit 1
